// Generated by LispyScript v1.0.0
var lib = require('lib');
var part = require("lib/lib/functional/partialApplication.js");
var curry = part["curry"];
var defer = part["defer"];
var router = require("./bin/router.js");
